In [114]:
df

,Classification,sum,CCTV installed before 2016,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Jongno-gu,2290,230,100,140,140,66,233,85,219,919,158
1,Zhonggu,3021,376,220,366,381,155,357,414,137,135,480
2,Yongsan-gu,3300,106,295,491,147,335,473,486,413,492,62
3,Seongdong-gu,4514,542,278,939,457,640,483,366,233,471,105
4,Gwangjin-gu,4156,403,42,666,460,712,191,740,273,340,329
5,Dongdaemun-gu,3446,0,657,670,199,215,229,226,317,755,178
6,Jungnang-gu,4512,479,153,170,215,1074,976,507,294,644,0
7,Seongbuk-gu,4543,320,380,382,758,662,206,398,353,414,670
8,Gangbuk-gu,3584,44,196,1,352,942,552,410,658,376,53
9,Dobong-gu,2378,3,68,80,152,149,156,552,557,661,0
10,Nowon-gu,3111,592,304,160,207,318,383,213,161,626,147
11,Eunpyeong-gu,5027,841,493,361,579,979,386,520,481,387,0
12,Seodaemun-gu,3799,505,304,546,364,401,613,425,213,422,6
13,Mapo-gu,3361,244,446,368,364,494,298,177,124,837,9
14,Yangcheon-gu,4447,220,418,566,827,321,352,347,386,1010,0
15,Gangseo-gu,3627,491,165,415,259,454,362,441,601,424,15
16,Guro-gu,5449,607,332,535,537,780,749,683,337,497,392
17,Geumcheon-gu,3170,92,130,196,539,366,514,207,304,822,0
18,Yeongdeungpo-gu,4697,727,284,356,673,66,1305,288,433,434,131
19,Dongjak-gu,3315,485,228,267,320,312,433,44,362,446,418
20,Gwanak-gu,5842,1025,607,675,663,889,404,549,135,602,293
21,Seocho-gu,5395,779,514,1022,422,339,419,565,878,457,0
22,Gangnam-gu,7721,1486,1280,981,735,787,913,505,588,446,0
23,Songpa-gu,4126,370,129,239,525,1042,237,148,380,943,113
24,Gangdong-gu,3549,725,202,273,377,356,614,262,381,359,0
25,Total,102380,11692,8225,10865,10652,12854,11838,9558,9218,13919,3559

In [89]:
# import pandas and read your csv file with it
import pandas as pd
df =

In [56]:
# store the first row of the table
temp = df.loc[0]
# shif up the values in the table by one row
for each in range(len(df)-2):
    df.loc[each] = df.loc[each+1]
# restore the original first row values of the table at the end of the table
df.loc[len(df)-1] = temp

In [90]:
df_shifted = df.shift(-1)
df_shifted.iloc[-1] = df.iloc[0]
df = df_shifted

In [91]:
df

,순번,구분,총 계,2016년 이전 설치된 CCTV,2016년,2017년,2018년,2019년,2020년,2021년,2022년,2023년,2024년
0,1.0,종로구,2290.0,230.0,100.0,140.0,140.0,66.0,233.0,85.0,219.0,919.0,158.0
1,2.0,중 구,3021.0,376.0,220.0,366.0,381.0,155.0,357.0,414.0,137.0,135.0,480.0
2,3.0,용산구,3300.0,106.0,295.0,491.0,147.0,335.0,473.0,486.0,413.0,492.0,62.0
3,4.0,성동구,4514.0,542.0,278.0,939.0,457.0,640.0,483.0,366.0,233.0,471.0,105.0
4,5.0,광진구,4156.0,403.0,42.0,666.0,460.0,712.0,191.0,740.0,273.0,340.0,329.0
5,6.0,동대문구,3446.0,0.0,657.0,670.0,199.0,215.0,229.0,226.0,317.0,755.0,178.0
6,7.0,중랑구,4512.0,479.0,153.0,170.0,215.0,1074.0,976.0,507.0,294.0,644.0,0.0
7,8.0,성북구,4543.0,320.0,380.0,382.0,758.0,662.0,206.0,398.0,353.0,414.0,670.0
8,9.0,강북구,3584.0,44.0,196.0,1.0,352.0,942.0,552.0,410.0,658.0,376.0,53.0
9,10.0,도봉구,2378.0,3.0,68.0,80.0,152.0,149.0,156.0,552.0,557.0,661.0,0.0
10,11.0,노원구,3111.0,592.0,304.0,160.0,207.0,318.0,383.0,213.0,161.0,626.0,147.0
11,12.0,은평구,5027.0,841.0,493.0,361.0,579.0,979.0,386.0,520.0,481.0,387.0,0.0
12,13.0,서대문구,3799.0,505.0,304.0,546.0,364.0,401.0,613.0,425.0,213.0,422.0,6.0
13,14.0,마포구,3361.0,244.0,446.0,368.0,364.0,494.0,298.0,177.0,124.0,837.0,9.0
14,15.0,양천구,4447.0,220.0,418.0,566.0,827.0,321.0,352.0,347.0,386.0,1010.0,0.0
15,16.0,강서구,3627.0,491.0,165.0,415.0,259.0,454.0,362.0,441.0,601.0,424.0,15.0
16,17.0,구로구,5449.0,607.0,332.0,535.0,537.0,780.0,749.0,683.0,337.0,497.0,392.0
17,18.0,금천구,3170.0,92.0,130.0,196.0,539.0,366.0,514.0,207.0,304.0,822.0,0.0
18,19.0,영등포구,4697.0,727.0,284.0,356.0,673.0,66.0,1305.0,288.0,433.0,434.0,131.0
19,20.0,동작구,3315.0,485.0,228.0,267.0,320.0,312.0,433.0,44.0,362.0,446.0,418.0
20,21.0,관악구,5842.0,1025.0,607.0,675.0,663.0,889.0,404.0,549.0,135.0,602.0,293.0
21,22.0,서초구,5395.0,779.0,514.0,1022.0,422.0,339.0,419.0,565.0,878.0,457.0,0.0
22,23.0,강남구,7721.0,1486.0,1280.0,981.0,735.0,787.0,913.0,505.0,588.0,446.0,0.0
23,24.0,송파구,4126.0,370.0,129.0,239.0,525.0,1042.0,237.0,148.0,380.0,943.0,113.0
24,25.0,강동구,3549.0,725.0,202.0,273.0,377.0,356.0,614.0,262.0,381.0,359.0,0.0
25,NaN,계,102380.0,11692.0,8225.0,10865.0,10652.0,12854.0,11838.0,9558.0,9218.0,13919.0,3559.0

In [74]:
# translate all elements in the table into English
from translate import Translator
translator = Translator(to_lang="en", from_lang="ko")

In [75]:
# collect the english columns 
eng_columns = list()
for each in df.columns:
    eng_columns.append(translator.translate(each))

In [92]:
df = df.rename(columns=dict(zip(df.columns, eng_columns)))

In [93]:
df.head()

,Number,Classification,sum,CCTV installed before 2016,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,1.0,종로구,2290.0,230.0,100.0,140.0,140.0,66.0,233.0,85.0,219.0,919.0,158.0
1,2.0,중 구,3021.0,376.0,220.0,366.0,381.0,155.0,357.0,414.0,137.0,135.0,480.0
2,3.0,용산구,3300.0,106.0,295.0,491.0,147.0,335.0,473.0,486.0,413.0,492.0,62.0
3,4.0,성동구,4514.0,542.0,278.0,939.0,457.0,640.0,483.0,366.0,233.0,471.0,105.0
4,5.0,광진구,4156.0,403.0,42.0,666.0,460.0,712.0,191.0,740.0,273.0,340.0,329.0

In [95]:
# where 1 is the axis number (0 for rows and 1 for columns.)
df =

In [97]:
df

,Classification,sum,CCTV installed before 2016,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,종로구,2290.0,230.0,100.0,140.0,140.0,66.0,233.0,85.0,219.0,919.0,158.0
1,중 구,3021.0,376.0,220.0,366.0,381.0,155.0,357.0,414.0,137.0,135.0,480.0
2,용산구,3300.0,106.0,295.0,491.0,147.0,335.0,473.0,486.0,413.0,492.0,62.0
3,성동구,4514.0,542.0,278.0,939.0,457.0,640.0,483.0,366.0,233.0,471.0,105.0
4,광진구,4156.0,403.0,42.0,666.0,460.0,712.0,191.0,740.0,273.0,340.0,329.0
5,동대문구,3446.0,0.0,657.0,670.0,199.0,215.0,229.0,226.0,317.0,755.0,178.0
6,중랑구,4512.0,479.0,153.0,170.0,215.0,1074.0,976.0,507.0,294.0,644.0,0.0
7,성북구,4543.0,320.0,380.0,382.0,758.0,662.0,206.0,398.0,353.0,414.0,670.0
8,강북구,3584.0,44.0,196.0,1.0,352.0,942.0,552.0,410.0,658.0,376.0,53.0
9,도봉구,2378.0,3.0,68.0,80.0,152.0,149.0,156.0,552.0,557.0,661.0,0.0
10,노원구,3111.0,592.0,304.0,160.0,207.0,318.0,383.0,213.0,161.0,626.0,147.0
11,은평구,5027.0,841.0,493.0,361.0,579.0,979.0,386.0,520.0,481.0,387.0,0.0
12,서대문구,3799.0,505.0,304.0,546.0,364.0,401.0,613.0,425.0,213.0,422.0,6.0
13,마포구,3361.0,244.0,446.0,368.0,364.0,494.0,298.0,177.0,124.0,837.0,9.0
14,양천구,4447.0,220.0,418.0,566.0,827.0,321.0,352.0,347.0,386.0,1010.0,0.0
15,강서구,3627.0,491.0,165.0,415.0,259.0,454.0,362.0,441.0,601.0,424.0,15.0
16,구로구,5449.0,607.0,332.0,535.0,537.0,780.0,749.0,683.0,337.0,497.0,392.0
17,금천구,3170.0,92.0,130.0,196.0,539.0,366.0,514.0,207.0,304.0,822.0,0.0
18,영등포구,4697.0,727.0,284.0,356.0,673.0,66.0,1305.0,288.0,433.0,434.0,131.0
19,동작구,3315.0,485.0,228.0,267.0,320.0,312.0,433.0,44.0,362.0,446.0,418.0
20,관악구,5842.0,1025.0,607.0,675.0,663.0,889.0,404.0,549.0,135.0,602.0,293.0
21,서초구,5395.0,779.0,514.0,1022.0,422.0,339.0,419.0,565.0,878.0,457.0,0.0
22,강남구,7721.0,1486.0,1280.0,981.0,735.0,787.0,913.0,505.0,588.0,446.0,0.0
23,송파구,4126.0,370.0,129.0,239.0,525.0,1042.0,237.0,148.0,380.0,943.0,113.0
24,강동구,3549.0,725.0,202.0,273.0,377.0,356.0,614.0,262.0,381.0,359.0,0.0
25,계,102380.0,11692.0,8225.0,10865.0,10652.0,12854.0,11838.0,9558.0,9218.0,13919.0,3559.0

In [102]:
# change all values as int
for each in df.columns[1:]:

In [103]:
df

,Classification,sum,CCTV installed before 2016,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,종로구,2290,230,100,140,140,66,233,85,219,919,158
1,중 구,3021,376,220,366,381,155,357,414,137,135,480
2,용산구,3300,106,295,491,147,335,473,486,413,492,62
3,성동구,4514,542,278,939,457,640,483,366,233,471,105
4,광진구,4156,403,42,666,460,712,191,740,273,340,329
5,동대문구,3446,0,657,670,199,215,229,226,317,755,178
6,중랑구,4512,479,153,170,215,1074,976,507,294,644,0
7,성북구,4543,320,380,382,758,662,206,398,353,414,670
8,강북구,3584,44,196,1,352,942,552,410,658,376,53
9,도봉구,2378,3,68,80,152,149,156,552,557,661,0
10,노원구,3111,592,304,160,207,318,383,213,161,626,147
11,은평구,5027,841,493,361,579,979,386,520,481,387,0
12,서대문구,3799,505,304,546,364,401,613,425,213,422,6
13,마포구,3361,244,446,368,364,494,298,177,124,837,9
14,양천구,4447,220,418,566,827,321,352,347,386,1010,0
15,강서구,3627,491,165,415,259,454,362,441,601,424,15
16,구로구,5449,607,332,535,537,780,749,683,337,497,392
17,금천구,3170,92,130,196,539,366,514,207,304,822,0
18,영등포구,4697,727,284,356,673,66,1305,288,433,434,131
19,동작구,3315,485,228,267,320,312,433,44,362,446,418
20,관악구,5842,1025,607,675,663,889,404,549,135,602,293
21,서초구,5395,779,514,1022,422,339,419,565,878,457,0
22,강남구,7721,1486,1280,981,735,787,913,505,588,446,0
23,송파구,4126,370,129,239,525,1042,237,148,380,943,113
24,강동구,3549,725,202,273,377,356,614,262,381,359,0
25,계,102380,11692,8225,10865,10652,12854,11838,9558,9218,13919,3559

In [108]:
# collect the english values
eng_values = list()
for each in df.Classification:

In [109]:
eng_values

['Jongno-gu',
 'Zhonggu',
 'Yongsan-gu',
 'Seongdong-gu',
 'Gwangjin-gu',
 'Dongdaemun-gu',
 'Jungnang-gu',
 'Seongbuk-gu',
 'Gangbuk-gu',
 'Dobong-gu',
 'Nowon-gu',
 'Eunpyeong-gu',
 'Seodaemun-gu',
 'Mapo-gu',
 'Yangcheon-gu',
 'Gangseo-gu',
 'Guro-gu',
 'Geumcheon-gu',
 'Yeongdeungpo-gu',
 'Dongjak-gu',
 'Gwanak-gu',
 'Seocho-gu',
 'Gangnam-gu',
 'Songpa-gu',
 'Gangdong-gu',
 'Total']

In [111]:
df['Classification'] = df['Classification'].map(dict(zip(df.Classification, eng_values)))

In [113]:
df

,Classification,sum,CCTV installed before 2016,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Jongno-gu,2290,230,100,140,140,66,233,85,219,919,158
1,Zhonggu,3021,376,220,366,381,155,357,414,137,135,480
2,Yongsan-gu,3300,106,295,491,147,335,473,486,413,492,62
3,Seongdong-gu,4514,542,278,939,457,640,483,366,233,471,105
4,Gwangjin-gu,4156,403,42,666,460,712,191,740,273,340,329
5,Dongdaemun-gu,3446,0,657,670,199,215,229,226,317,755,178
6,Jungnang-gu,4512,479,153,170,215,1074,976,507,294,644,0
7,Seongbuk-gu,4543,320,380,382,758,662,206,398,353,414,670
8,Gangbuk-gu,3584,44,196,1,352,942,552,410,658,376,53
9,Dobong-gu,2378,3,68,80,152,149,156,552,557,661,0
10,Nowon-gu,3111,592,304,160,207,318,383,213,161,626,147
11,Eunpyeong-gu,5027,841,493,361,579,979,386,520,481,387,0
12,Seodaemun-gu,3799,505,304,546,364,401,613,425,213,422,6
13,Mapo-gu,3361,244,446,368,364,494,298,177,124,837,9
14,Yangcheon-gu,4447,220,418,566,827,321,352,347,386,1010,0
15,Gangseo-gu,3627,491,165,415,259,454,362,441,601,424,15
16,Guro-gu,5449,607,332,535,537,780,749,683,337,497,392
17,Geumcheon-gu,3170,92,130,196,539,366,514,207,304,822,0
18,Yeongdeungpo-gu,4697,727,284,356,673,66,1305,288,433,434,131
19,Dongjak-gu,3315,485,228,267,320,312,433,44,362,446,418
20,Gwanak-gu,5842,1025,607,675,663,889,404,549,135,602,293
21,Seocho-gu,5395,779,514,1022,422,339,419,565,878,457,0
22,Gangnam-gu,7721,1486,1280,981,735,787,913,505,588,446,0
23,Songpa-gu,4126,370,129,239,525,1042,237,148,380,943,113
24,Gangdong-gu,3549,725,202,273,377,356,614,262,381,359,0
25,Total,102380,11692,8225,10865,10652,12854,11838,9558,9218,13919,3559